config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      as :user do
        post '/registrations' => 'registrations#create'
        post '/sign-in' => 'sessions#create'
        delete '/sign-out' => 'sessions#destroy'
        resource :profiles do
          get :me
        end
      end
    end
  end

  resources :teams do
    resources :collaborators, shallow: true, only: %i(new create update destroy)
    resources :tasks, shallow: true do
      put '/:state', to: 'tasks#set_state', as: :state
    end
    get 'collaborators/staff'
  end
  # /my-:param(-can-be-:optional)(-and-this-:too)
  get 'collaborators/staff'
  get 'home/index'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @collaborators = current_user.awaiting_collaborators.includes(:team)
    @approved_teams = Team.where(id: current_user.approved_collaborators.pluck(:team_id))
  end
end

app/views/home/index.html.slim
- provide(:title, t('home.title1'))
h1 = yield(:title)

.row
  .col-xs-12
    .panel-group#myTasks
      .panel.panel-default
        .panel-heading = t('task.my_tasks')
        .panel-body
          table.table
            thead
              tr
                th = t('activerecord.attributes.task.title')
                th = t('task.type')
                th = t('task.state')
            tbody
              - current_user.tasks.ready.each do |t|
                tr id="task#{t.id}"
                  td = link_to t.title, task_path(t.id)
                  td = t("activerecord.attributes.task.type.#{t.task_type}")
                  td = t("activerecord.attributes.task.state.#{t.state}")

.row
  .col-xs-12
    .panel.panel-default
      .panel-heading = t('team.index')
      .panel-body
        .panel-group#userOwnTeams
          - current_user.teams.each do |t|
            .panel.panel-default
              .panel-body
                = link_to t.title, team_path(t.id), id: "ownTeam#{t.id}"
.row
  .col-md-7
    .panel.panel-default#awaitingCollTeams
      .panel-heading = t('home.title3')
      .panel-body
        table.table
          thead
            tr
              th = t('team.name')
              th.text-center = t('team.approve')
              th.text-center = t('team.reject')
          tbody
            - @collaborators.each do |c|
              tr id="appWaiting#{c.id}"
                td = c.team.title
                td.text-center
                  = link_to collaborator_path(c.id, status: :approved),
                          id: "approve#{c.id}",
                          method: :patch,
                          class: 'js-coll btn btn-sm btn-success',
                          data: {type: :json, action: 'approve', remote: true} do
                    = fa_icon 'flag-o'
                td.text-center
                  = link_to collaborator_path(c.id, status: :rejected),
                          id: "reject#{c.id}",
                          method: :patch,
                          class: 'js-coll btn btn-sm btn-danger',
                          data: {type: :json, action: 'reject', remote: true} do
                    = fa_icon 'close'

  .col-md-5
    .panel.panel-default
      .panel-heading = t('home.title4')
      .panel-body
        .panel-group#userCollTeams
          - @approved_teams.each do |t|
            .panel.panel-default
              .panel-body
                p id="collTeam#{t.id}" = t.title