config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      as :user do
        post '/registrations' => 'registrations#create'
        post '/sign-in' => 'sessions#create'
        delete '/sign-out' => 'sessions#destroy'
        resource :profiles do
          get :me
        end
      end
    end
  end

  resources :teams do
    resources :collaborators, shallow: true, only: %i(new create update destroy)
    resources :tasks, shallow: true do
      put '/:state', to: 'tasks#set_state', as: :state
    end
    get 'collaborators/staff'
  end
  # /my-:param(-can-be-:optional)(-and-this-:too)
  get 'collaborators/staff'
  get 'home/index'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/views/layouts/_js_locales_info.html.slim
= javascript_tag do
  |  I18n.defaultLocale = "
  = I18n.default_locale
  | "; I18n.locale = "
  = I18n.locale
  | "; I18n.fallbacks = true; 

app/views/layouts/_navbar.html.slim
.container-fluid
  nav.navbar.navbar-default.navbar-xs role="navigation"
    .navbar-header
      button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/"
        b Team aggregator
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        - if user_signed_in?
          li.dropdown  title="#{t('profile')}"
            a.dropdown-toggle data-toggle="dropdown" href="#"
              = fa_icon 'user'
              b.caret
            ul.dropdown-menu
              li
                a data-method="delete" href="#{destroy_user_session_path}" rel="nofollow" = t('sign_out')
              li.divider
              li
                = link_to t('edit_user'), edit_user_registration_path
          li.dropdown data-toggle="tooltip" data-placement="bottom" title="#{t('activerecord.models.team.many')}"
            a.dropdown-toggle data-toggle="dropdown" href="#"
              = fa_icon 'group'
              b.caret
            ul.dropdown-menu
              li
                = link_to t('team.add'), new_team_path
              li.divider
              li
                = link_to t('team.index'), teams_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang=<%= I18n.locale %>>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= 'TestApp ' + yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/js_locales_info' %>
    <%= render_flash %>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development?%>
    </div>
  </body>
</html>